### ISSUE TITLE
Manual, videos or usage examples?

### ISSUE THREAD

**Issue by lgcambero** [Invoke-IR/PowerForensics#109]

**Comment by jaredcatkinson** [comment]
Hi Igcambero,

Every cmdlet has help (similar to man pages in unix) that include examples.  
- You can list cmdlets using the following cmdlet "Get-Command -Module PowerForensics"
- To list cmdlet help you can use type "help Get-ForensicFileRecord" or "help Get-ForensicFileRecord -Examples"

Regarding videos, I plan on making some instructional videos at some point, but haven't had time yet.

**Comment by lgcambero** [comment]
Thank you, it would be interesting to see some practical examples of use. Regards.
