### ISSUE TITLE
not apply to EFI System

### ISSUE THREAD

**Issue by horse9153** [Invoke-IR/PowerForensics#119]
basic user to power forensic.
studying not apply to efi system in today.
analysis is added to efi system.

thank you. :)

**Comment by jaredcatkinson** [comment]
horse9153,

I may need a bit of clarification on what you are looking for, but generally the boot sector on an EFI formatted disk is composed of a Guid Partition Table.  This is the only difference between EFI and BIOS (as far as I'm aware).

You can parse the Guid Partition Table with the Get-ForensicGuidPartitionTable or Get-ForensicBootSector cmdlets.

ex. Get-ForensicBootSector -Path \.\PHYSICALDRIVE0

Please let me know if that does not answer your question.

**Comment by horse9153** [comment]
thank you for answer email.

more studying to powerforensics and powershell.

send to answer email for me. tahnk you. J

forward to full happy day…
