### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by JamesHabben** [Invoke-IR/PowerForensics#133]
I tried building the project without changing any of the source code, and I get this error in VS2015.

Error   CS0592  Attribute 'Alias' is not valid on this declaration type. It is only valid on 'property, indexer, field' declarations.

One line that causes the error:
[Alias("4n6dd")]

I get it for the following files:
...\Cmdlets\BinShred\BinShredCommand.cs 11
...\Cmdlets\ForensicTimeline\Get-ForensicTimeline.cs    16
...\Cmdlets\Utilities\Get-ForensicChildItem.cs  9
...\Cmdlets\Utilities\Get-ForensicContent.cs    12
...\Cmdlets\Utilities\Invoke-ForensicDD.cs  12

Is there some setting I need to change?

**Comment by jaredcatkinson** [comment]
You can just remove the [Alias()] block from the code.  Doesn't really
affect anything.  I've found that the Alias block is not available in all
versions of the System.Management.Automation assembly, so I am actually
removing it from the next release anyway.

**Comment by JamesHabben** [comment]
Your latest commit removed most of them, and that fixed the build problem.

Is there an easier way of using these built DLL's or do I have to follow the instructions on your readme every time I make a build?

**Comment by jaredcatkinson** [comment]
Can you check to see if this is still an issue in the latest commit?
