### ISSUE TITLE
Debug issue

### ISSUE THREAD

**Issue by suminvr** [Invoke-IR/PowerForensics#139]
Getting the following error while trying to run the C# code of powerforensics

A project with an output type of class library cannot be started directly
In order to debug this project,add an executable solution to this project which references the library project.

Need a solution to fix this issue

**Comment by suminvr** [comment]
![debug error](https://cloud.githubusercontent.com/assets/17265052/13067739/cc589ad6-d499-11e5-9ee2-5b32275c79da.jpg)

**Comment by jaredcatkinson** [comment]
If you are trying to debug PowerForensics you want to follow the instructions in this article http://www.powershellmagazine.com/2014/04/08/basics-of-writing-a-powershell-module-with-c-part-2-debugging/.

**Comment by suminvr** [comment]
Thanks.That fixed the issue
