### ISSUE TITLE
Copy-ForensicFile issue

### ISSUE THREAD

**Issue by alexandreborges** [Invoke-IR/PowerForensics#142]
Jared, 

Good morning. How are you?

I've used the PowerForensics (it is excellent), but today a issue came up.  Why does the following command not work?

PS C:\Users\Administrator> **Copy-ForensicFile -Path 'C:\Windows\System32\config\SOFTWARE' -Destination C:\powerforensics\SOFTWARE_1**

Copy-ForensicFile : **_Could not locate desired stream_**
At line:1 char:1
- Copy-ForensicFile -Path 'C:\Windows\System32\config\SOFTWARE' -Destin ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Copy-ForensicFile], Exception
  - FullyQualifiedErrorId : System.Exception,PowerForensics.Cmdlets.CopyFileCommand

PS C:\Windows\system32\config> **Get-ForensicFileRecord -Path C:\Windows\System32\config\SOFTWARE**

FullName             : C:\Windows\System32\config\SOFTWARE
Name                 : SOFTWARE
SequenceNumber       : 1
RecordNumber         : 70431
ParentSequenceNumber : 1
ParentRecordNumber   : 2718
Directory            : False
Deleted              : False
ModifiedTime         : 10/5/2016 5:13:54 AM
AccessedTime         : 10/5/2016 2:37:00 AM
ChangedTime          : 10/5/2016 5:13:54 AM
BornTime             : 7/14/2009 2:34:08 AM
FNModifiedTime       : 7/12/2014 5:17:21 AM
FNAccessedTime       : 7/12/2014 5:17:21 AM
FNChangedTime        : 7/12/2014 5:17:21 AM
FNBornTime           : 7/12/2014 5:17:21 AM

Ok, I know that Copy-ForensicFile is the easier way, but I couldn't understand that I have only faced problems with this hive file. By using this same command with all other hiver, everything goes fine:

PS C:\Users\Administrator> **Copy-ForensicFile -Path C:\Windows\System32\config\SYSTEM -Destination C:\powerforensics\SYSTEM_1**
PS C:\Users\Administrator> **Copy-ForensicFile -Path C:\Windows\System32\config\SECURITY -Destination C:\powerforensics\SECURITY_1**
PS C:\Users\Administrator> **Copy-ForensicFile -Path 'C:\Users\Administrator\AppData\Local\Microsoft\Windows\UsrClass.dat' -Destination 'C:\powerforensics\UsrClass_1'**
PS C:\Users\Administrator> **Copy-ForensicFile -Path C:\Windows\System32\config\SAM -Destination C:\powerforensics\SAM_1**

Certainly, I am missing something (by the way, it's later midnight here and I am so tired). 

It follows the directory listing; 

PS C:\Windows\system32\config> **ls**

Directory: C:\Windows\system32\config

Mode                LastWriteTime         Length Name

---

d-----        7/13/2009  11:34 PM                Journal
d-----        10/1/2016   9:08 PM                RegBack
d-----        6/18/2015   5:18 PM                systemprofile
d-----        5/28/2015   3:57 AM                TxR
-a----        7/12/2014   2:17 AM          28672 BCD-Template
-a----        10/4/2016  10:16 PM       59244544 COMPONENTS
              10/4/2016  11:54 PM        4718592 DEFAULT
-a----        5/30/2016   2:48 AM            128 netlogon.ftl
              10/4/2016  11:38 PM         262144 SAM
              10/4/2016  11:54 PM         262144 SECURITY
              10/5/2016   2:05 AM      106692608 SOFTWARE
              10/5/2016   2:05 AM       13369344 SYSTEM

Please, forgive me for the simple question. 

I hope you have a nice day and thank you for your help. 

Alexandre.

**Comment by jaredcatkinson** [comment]
Alexandre,

Thanks for reaching out! Your issue may be a symptom of the DATA attribute for the SOFTWARE hive being referenced as part of an ATTRIBUTE_LIST attribute.

Try running the following command:
`Get-ForensicFileRecord -Path C:\Windows\system32\config\SOFTWARE | select -ExpandProperty Attribute`

If you see something like this: 
Name                 : STANDARD_INFORMATION
AttributeId          : 0
NameString           :
ModifiedTime         : 8/12/2016 9:11:51 PM
AccessedTime         : 8/12/2016 9:11:51 PM
ChangedTime          : 12/30/2015 1:56:29 PM
BornTime             : 10/30/2015 6:28:30 AM
Permissions          :
UpdateSequenceNumber : 2938924896

**AttributeReference : {STANDARD_INFORMATION, FILE_NAME, DATA, DATA}
Name               : ATTRIBUTE_LIST
NameString         :
AttributeId        : 4**

Filename             : SOFTWARE
ParentSequenceNumber : 3
ParentRecordNumber   : 196470
Namespace            : 0
AllocatedSize        : 0
RealSize             : 0
Flags                : 32
ER                   : 0
ModifiedTime         : 12/17/2015 10:17:35 AM
AccessedTime         : 12/17/2015 10:17:35 AM
ChangedTime          : 12/17/2015 10:17:35 AM
BornTime             : 12/17/2015 10:17:35 AM
Name                 : FILE_NAME
NameString           :
AttributeId          : 2

then the ATTRIBUTE_LIST is the culprit.

**Comment by jaredcatkinson** [comment]
If this is the problem, you can get your result by digging into the ATTRIBUTE_LIST attribute.

```
$r = Get-ForensicFileRecord -Path C:\Windows\System32\config\SOFTWARE
$attr = $r.Attribute | Where-Object {$_.Name -eq 'ATTRIBUTE_LIST'}
$attr.AttributeReference
```

```
Name                     RecordNumber   SequenceNumber     NameString
----                     ------------   --------------     ----------
STANDARD_INFORMATION     278650                1
FILE_NAME                278650                1
DATA                     14562                 7
```

The output is telling us that the DATA attribute (the pointer to the contents of the SOFTWARE hive) is being stored in a different MFT record (#14562).

Now we can use this information to copy the file using Get-ForensicFileRecord like so:
`(Get-ForensicFileRecord -VolumeName \\.\C: -Index 14562).CopyFile('C:\powerforensics\SOFTWARE_1')`

**Comment by jaredcatkinson** [comment]
This is something that I'd like to make transparent at some point... I just haven't had the time.

**Comment by alexandreborges** [comment]
Jared, 

Good afternoon. Thank you for your explanation so much. Honestly, I didn't imagine that could be a problem related to attributes. 

The second answer will be very useful. This time, I am working on another notebook, but later I will test your explanation to check whether everything works fine (certainly it does). 

I know that your time is really tight, however you could write a article explaining these facts and effects. It would be a nice write up.  

Powerforensic is one of most impressive framework that I have ever seen. During my talks and classes, I intend to use it because it is excellent. Furthermore, I want to encourage other professionals to use it. 

Once more, thank you for your time, Jared, and later I return to tell you whether everything worked as expected. 

Have a nice day and take care.

Alexandre.

**Comment by alexandreborges** [comment]
Jared, good evening. How are you? 

I am sorry for the delay, but I had a taugh day yesterday. 

You are right about your suggestion, but I have another question. It follows my output:

PS C:\Users\Administrator> **Import-Module PowerForensics**
PS C:\Users\Administrator> **Get-ForensicFileRecord -Path C:\Windows\system32\config\SOFTWARE | select -ExpandProperty Attribute**

Name                 : STANDARD_INFORMATION
AttributeId          : 0
NameString           :
ModifiedTime         : 10/6/2016 11:36:21 PM
AccessedTime         : 10/5/2016 6:22:54 AM
ChangedTime          : 10/6/2016 11:36:21 PM
BornTime             : 7/14/2009 2:34:08 AM
Permissions          :
UpdateSequenceNumber : 967304880

AttributeReference : {STANDARD_INFORMATION, FILE_NAME, **DATA, DATA**}
Name               : **ATTRIBUTE_LIST**
NameString         :
AttributeId        : 4

Filename             : SOFTWARE
ParentSequenceNumber : 1
ParentRecordNumber   : 2718
Namespace            : 0
AllocatedSize        : 0
RealSize             : 0
Flags                : 32
ER                   : 0
ModifiedTime         : 7/12/2014 5:17:21 AM
AccessedTime         : 7/12/2014 5:17:21 AM
ChangedTime          : 7/12/2014 5:17:21 AM
BornTime             : 7/12/2014 5:17:21 AM
Name                 : FILE_NAME
NameString           :
AttributeId          : 2

Thus, as you explained me, likely the ATTRIBUTE_LIST is the culprit. However, it follow other information: 

PS C:\Users\Administrator> **$r = Get-ForensicFileRecord -Path C:\Windows\System32\config\SOFTWARE**
PS C:\Users\Administrator> **$attr = $r.Attribute | Where-Object {$_.Name -eq 'ATTRIBUTE_LIST'}**
PS C:\Users\Administrator> **$attr.AttributeReference**

Name                                     RecordNumber SequenceNumber NameString

---

STANDARD_INFORMATION        70431              1
FILE_NAME                                   70431              1
**DATA                                          172263             28
DATA                                          232574              6**

It seems that the information is spread over two different MTF records. Moving forward, I found that only one MTF record holds information: 

PS C:\Users\Administrator> **(Get-ForensicFileRecord -VolumeName \.\C: -Index 232574).CopyFile('C:\powerforensics\SOFTWARE_1a')**

PS C:\Users\Administrator> **ls C:\powerforensics\SOFTWARE_1***

```
Directory: C:\powerforensics
```

Mode                LastWriteTime              Length               Name

---

-a----              10/6/2016   8:36 PM      **106692608        SOFTWARE_1
-a----              10/6/2016   8:50 PM              **0                SOFTWARE_1a**

Ok, eventually I have found the information, but I am concerned when I find information at two places. How can I join them? I think I would have to analyze both separately. 

Jared, I know that your time is complicated, but any professional who doesn't know about the structure of a MTF and NTFS filesystem can face problems with PowerForensics. Therefore, If someday you have time, my suggestion is that you could write a tutorial and/or a book (I know that is not a good idea, but your project deserves a book). 

I also know that you have written (on the same site) many articles covering these structures, but this information could be placed together in a logical sequence.  

Once more, thank you for your kindness. Today I showed the PowerForensic for few professionals during a presentation and everyone loved it. 

I hope you have a nice day, Jared. 

Alexandre.

**Comment by jaredcatkinson** [comment]
Alexandre,

I just found an example of this same behavior on one of my test VMs. I honestly can't say what the relationship is between the two DATA attributes. I'm not sure if one is old and one is new, or if they need to be combined. I'll keep looking into it and see what I can find.

Thanks for spreading the word and using PF!
- Jared

**Comment by alexandreborges** [comment]
Jared, 

Good evening. Thank you for the message. 

Certainly, I will continue spreading the word because PF is really amazing. I hope I can bring new issues for improving the PF experience. 

Have a nice day, Jared. Take care.

Alexandre.

**Comment by jaredcatkinson** [comment]
Hey Alexandre,

I fixed the issue with ATTRIBUTE_LIST attributes in one of my recent commits, so you should not see this issue if you download the latest version. You have to download from the Modules\PowerForensics directory as I have not created a new release yet.
- Jared

**Comment by alexandreborges** [comment]
Jared, 

Good afternoon. Thank you for that so much. I will check it. :)

I hope you have a nice day.

Alexandre.
