### ISSUE TITLE
Invoke-ForensicBinShred should support byte arrays

### ISSUE THREAD

**Issue by mattifestation** [Invoke-IR/PowerForensics#77]
I would need Invoke-ForensicBinShred to support something like this:

``` powershell
Invoke-ForensicBinShred -Bytes $BinaryBytes
```

Thanks!

**Comment by LeeHolmes** [comment]
Fixed in https://github.com/Invoke-IR/PowerForensics/commit/61035a89a456c5d0886cf64c321472eefe4560e3
