### ISSUE TITLE
Rename Invoke-ForensicBinShred to ConvertFrom-BinaryData (leaving 'BinShred' alias)

### ISSUE THREAD

**Issue by juneb** [Invoke-IR/PowerForensics#79]
The Invoke-ForensicBinShred cmdlet parses a binary file and retrieves its contents. But, when I looked up "shred" and "shredding," I found articles, tools, and algorithms for erasing or zeroing out files and drives, not parsing.

Can you please link me to the definition of "shred" that you're using in this cmdlet? Thanks.

**Comment by jaredcatkinson** [comment]
I'll run this by Lee to see what his thought process was on the name.  I'd imagine he is using some sort of colloquialism for "shredding" binary data into structured data.

**Comment by juneb** [comment]
Great. Thanks.

**Comment by jaredcatkinson** [comment]
From Lee "Shredding: Breaking a monolithic thing into its constituent parts. 
Invoke-BinShred is a crappy name. It should be something like ConvertFrom-BinaryData, with an alias 'binshred'"

**Comment by juneb** [comment]
Thanks for checking on it. Are you going to change the name? Either way is fine with me.

**Comment by LeeHolmes** [comment]
Yes, a name change makes sense. I'll close this issue when it happens :)

**Comment by LeeHolmes** [comment]
Fixed with https://github.com/Invoke-IR/PowerForensics/commit/61035a89a456c5d0886cf64c321472eefe4560e3
