### ISSUE TITLE
Invoke-ForensicDD -Offset is mandatory

### ISSUE THREAD

**Issue by juneb** [Invoke-IR/PowerForensics#80]
This might be a silly question, because I have no domain knowledge, but why is the Offset parameter of Invoke-ForensicDD mandatory? Shouldn't it be optional with a default value of 0?

**Comment by jaredcatkinson** [comment]
Great catch June!  I will update the code.  What do you think about the BlockSize default value being set to 512 (the size of a disk Sector) as well?

**Comment by juneb** [comment]
Thanks. The BlockSize seems fine to me, but, again, I have no domain knowledge, so I'll leave that up to you. You might want to make Count optional with a default of 1.

**Comment by jaredcatkinson** [comment]
This is taken care of. Offset now has a default of 0 and BlockSize has a default of 512.
