### ISSUE TITLE
Cmdlets require Unix-style volume format

### ISSUE THREAD

**Issue by juneb** [Invoke-IR/PowerForensics#82]
In Windows and Windows PowerShell, drives and volumes are typically specified as C: or C:. The cmdlets in PowerForensics require what I think is a Unix-style specification, e.g. \.\C:

To make this easy for PowerShell users, it would be great to let them input volumes in Windows style and then convert the input to Unix style. (Or change the cmdlets to process Windows-style naming).

If this isn't acceptable, at least the error message should show the required format.

Change:
Invoke-ForensicTimeline : Provided Volume Name is not acceptable.

To:
The VolumeName value is not in the correct format. Enter a Unix-format name, such as \.\C:, instead of C: or C:.

[ADMIN]: PS C:> $r = Invoke-ForensicTimeline -VolumeName \.\C:

[ADMIN]: PS C:> $r = Invoke-ForensicTimeline -VolumeName C:
Invoke-ForensicTimeline : Provided Volume Name is not acceptable.
At line:1 char:6
- $r = Invoke-ForensicTimeline -VolumeName C:
-      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Invoke-ForensicTimeline], Exception
  - FullyQualifiedErrorId : System.Exception,PowerForensics.Cmdlets.InvokeForensicTimelineCommand

**Comment by jaredcatkinson** [comment]
The CreateFile API call requires the \.\C: format, but I currently accept both \.\C: and C.  I'll add C: as an acceptable input.

**Comment by juneb** [comment]
Terrific. I'll add that detail to the help topics. If I miss an instance, be sure to let me know.

**Comment by jaredcatkinson** [comment]
This has been fixed! -VolumeName now accepts the following formats \.\C:, C:, or C

**Comment by juneb** [comment]
Great. Can you please fix the error message, too. It's best when the error message helps the user to correct their mistake. 

The VolumeName value is not in the correct format. Use one of the following formats:  .\C:, C:, or C.

**Comment by jaredcatkinson** [comment]
Error message is fixed as well :-)

**Comment by jaredcatkinson** [comment]
There are likely a lot of error messages that need fixing!
