### ISSUE TITLE
Format-ForensicHex is not present in 1.0.1.0

### ISSUE THREAD

**Issue by juneb** [Invoke-IR/PowerForensics#87]
Just making sure this is intentional. The cmdlets are missing from the dll and from the ExportedCmdlets list in the .psd1. 

Many of the examples use Format-ForensicHex. Do you want to replace them with references to the Format-Hex and Get-FileHash cmdlets in Microsoft.PowerShell.Utility?

**Comment by jaredcatkinson** [comment]
It is intentional. Lee convinced me to remove Get-ForensicHash and Format-ForensicHex in favor of Get-FileHash & Format-Hex.

**Comment by jaredcatkinson** [comment]
I can fix the examples :-)

**Comment by juneb** [comment]
Too late! I fixed them. :)

Don't worry about the docs unless something is wrong. Then, be sure to tell me, so I'll learn.
