### ISSUE TITLE
Question: Get-ForensicBootSection -Path parameter values (and error message)

### ISSUE THREAD

**Issue by juneb** [Invoke-IR/PowerForensics#88]
What is an acceptable value for the Path parameter of Get-ForensicBootSector and how do you get it? (Sorry, I bet this is a very naïve question.

I tried 'C' and 'D' in all of their formats (//./C, C:, C) and then I got the volume name (gwmi win32_logicaldisk | driveType -eq '3').VolumeName and tried the different formats of that value, but I got the same (not particularly helpful) error:

Get-ForensicBootSector : Provided Drive Name is not acceptable.

**Comment by jaredcatkinson** [comment]
Get-ForensicBootSector, Get-ForensicMasterBootRecord, Get-ForensicGuidPartitionTable, and Get-ForensicPartitionTable all refer to the Physical Drive itself instead of the Logical Volume.  Because of this the -DriveName parameter takes \.\PHYSICALDRIVE0.

**Comment by jaredcatkinson** [comment]
You can list your physical drives using "gwmi win32_diskdrive | select DeviceId"

**Comment by jaredcatkinson** [comment]
That single physical drive may contain a number of partitions which are the logical volumes that we refer to in the rest of the cmdlets.

**Comment by jaredcatkinson** [comment]
Unfortunately Get-ForensicGuidPartitionTable won't work unless you have a Guid Partition Table formatted disk.

**Comment by juneb** [comment]
Thanks. Got it. Makes sense.
